version: "3.9"

services:
  FinanceAllianx-database:
    image: krylixza/FinanceAllianx-database:latest
    container_name: FinanceAllianx-database
    networks:
      - FinanceAllianx
    ports:
      - 3306:3306

  FinanceAllianx-web-api:
    image: krylixza/FinanceAllianx-web-api:latest-arm
    container_name: FinanceAllianx-web-api
    depends_on: 
      - FinanceAllianx-database
    networks:
      - FinanceAllianx
    ports: 
      - 5000:5000

networks:
  FinanceAllianx:
